CREATE TRIGGER `after_delivery_delete` AFTER DELETE ON `DELIVERY`
 FOR EACH ROW BEGIN
  -- INVENTORY 테이블에 해당 PRODUCT_NO가 있는지 확인
  IF EXISTS (SELECT * FROM INVENTORY WHERE PRODUCT_NO = OLD.PRODUCT_NO) THEN
    -- SUM_COUNT 값을 증가시킴
    UPDATE INVENTORY
    SET SUM_COUNT = SUM_COUNT + OLD.COUNT, DATE = current_timestamp()
    WHERE PRODUCT_NO = OLD.PRODUCT_NO;
  ELSE
    -- INVENTORY 테이블에 해당 PRODUCT_NO가 없다면 새 항목을 추가
    INSERT INTO INVENTORY (PRODUCT_NO, SUM_COUNT, DATE)
    VALUES (OLD.PRODUCT_NO, OLD.COUNT, current_timestamp());
  END IF;
END

CREATE TRIGGER `after_delivery_insert` AFTER INSERT ON `DELIVERY`
 FOR EACH ROW BEGIN
  -- INVENTORY 테이블에 해당 PRODUCT_NO가 있는지 확인
  IF EXISTS (SELECT * FROM INVENTORY WHERE PRODUCT_NO = NEW.PRODUCT_NO) THEN
    -- SUM_COUNT 값을 감소시킴
    UPDATE INVENTORY
    SET SUM_COUNT = SUM_COUNT - NEW.COUNT, DATE = current_timestamp()
    WHERE PRODUCT_NO = NEW.PRODUCT_NO;
    
    -- SUM_COUNT가 0보다 작아지면 해당 항목을 삭제
    DELETE FROM INVENTORY
    WHERE PRODUCT_NO = NEW.PRODUCT_NO AND SUM_COUNT <= 0;
  END IF;
END

CREATE TRIGGER `after_stock_delete` AFTER DELETE ON `STOCK`
 FOR EACH ROW BEGIN
  -- INVENTORY 테이블에 해당 PRODUCT_NO가 있는지 확인
  IF EXISTS (SELECT * FROM INVENTORY WHERE PRODUCT_NO = OLD.PRODUCT_NO) THEN
    -- SUM_COUNT 값을 감소시킴
    UPDATE INVENTORY
    SET SUM_COUNT = SUM_COUNT - OLD.COUNT, DATE = current_timestamp()
    WHERE PRODUCT_NO = OLD.PRODUCT_NO;
    
    -- SUM_COUNT가 0보다 작아지면 해당 항목을 삭제
    DELETE FROM INVENTORY
    WHERE PRODUCT_NO = OLD.PRODUCT_NO AND SUM_COUNT <= 0;
  END IF;
END

CREATE TRIGGER `after_stock_insert` AFTER INSERT ON `STOCK`
 FOR EACH ROW BEGIN
  -- INVENTORY 테이블에 해당 PRODUCT_NO가 있는지 확인
  IF EXISTS (SELECT * FROM INVENTORY WHERE PRODUCT_NO = NEW.PRODUCT_NO) THEN
    -- 존재하면 SUM_COUNT 값을 증가시킴
    UPDATE INVENTORY
    SET SUM_COUNT = SUM_COUNT + NEW.COUNT, DATE = current_timestamp()
    WHERE PRODUCT_NO = NEW.PRODUCT_NO;
  ELSE
    -- 존재하지 않으면 새로운 항목을 삽입
    INSERT INTO INVENTORY (PRODUCT_NO, SUM_COUNT, DATE)
    VALUES (NEW.PRODUCT_NO, NEW.COUNT, current_timestamp());
  END IF;
END