CREATE TABLE BOARD_ATTACHMENT (
    ATTACHMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    MIME_TYPE VARCHAR(100),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES BOARD_POST(POST_ID) ON DELETE CASCADE
);
