CREATE TABLE PRODUCTION (
  ID INT PRIMARY KEY,
  PROCESSCODE VARCHAR(50),
  LOT VARCHAR(30),
  QUANTITY INT,
  DESCRIPTION TEXT
);

CREATE TABLE SCANNED_BARCODE (
  ID INT PRIMARY KEY,
  BARCODE VARCHAR(50),
  PROCESSCODE VARCHAR(50),
  SCAN_DATE DATE,
  BOX_LABEL VARCHAR(50),
);
CREATE TABLE BOX (
    NO INT AUTO_INCREMENT PRIMARY KEY,
    PROCESSCODE VARCHAR(50),
    LOT VARCHAR(30),
    BOX_NO INT,  -- 박스 번호 (각 제품별로 고유)
    BARCODE_COUNT INT,  -- 박스에 담긴 바코드 수량
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OUT_DATE DATE,
    STATE INT
 
);
CREATE TABLE INVENTORY (
  ID INT PRIMARY KEY,
  PRODUCT_NO INT,
  QUANTITY INT,
  LAST_UPDATED DATE,
  FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCTS(NO)
);